from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1248, 831)
        Form.setWindowOpacity(11.0)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1221, 801))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane\n"
"{\n"
"    top: -8px;\n"
"}\n"
" \n"
"QTabWidget::tab-bar\n"
"{\n"
"    alignment: center;\n"
"}")
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(540, 700, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.repeat_count_2 = QtWidgets.QSpinBox(self.tab)
        self.repeat_count_2.setGeometry(QtCore.QRect(865, 643, 90, 22))
        self.repeat_count_2.setObjectName("repeat_count_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(250, 523, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.repeat_count_1 = QtWidgets.QSpinBox(self.tab)
        self.repeat_count_1.setGeometry(QtCore.QRect(865, 563, 90, 22))
        self.repeat_count_1.setObjectName("repeat_count_1")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(250, 153, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.comboBox_matrix = QtWidgets.QComboBox(self.tab)
        self.comboBox_matrix.setGeometry(QtCore.QRect(640, 90, 315, 31))
        self.comboBox_matrix.setObjectName("comboBox_matrix")
        self.comboBox_crossover = QtWidgets.QComboBox(self.tab)
        self.comboBox_crossover.setGeometry(QtCore.QRect(640, 330, 315, 31))
        self.comboBox_crossover.setObjectName("comboBox_crossover")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(250, 273, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(250, 603, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(390, 20, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.label.setToolTipDuration(4)
        self.label.setMidLineWidth(12)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(250, 563, 591, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(250, 180, 381, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(250, 483, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.launch_count = QtWidgets.QSpinBox(self.tab)
        self.launch_count.setGeometry(QtCore.QRect(865, 403, 90, 22))
        self.launch_count.setObjectName("launch_count")
        self.p_mutation = QtWidgets.QSpinBox(self.tab)
        self.p_mutation.setGeometry(QtCore.QRect(865, 483, 90, 22))
        self.p_mutation.setObjectName("p_mutation")
        self.generation_size_2 = QtWidgets.QSpinBox(self.tab)
        self.generation_size_2.setGeometry(QtCore.QRect(865, 603, 90, 22))
        self.generation_size_2.setObjectName("generation_size_2")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(250, 333, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.comboBox_model = QtWidgets.QComboBox(self.tab)
        self.comboBox_model.setGeometry(QtCore.QRect(640, 150, 315, 31))
        self.comboBox_model.setObjectName("comboBox_model")
        self.p_crossover = QtWidgets.QSpinBox(self.tab)
        self.p_crossover.setGeometry(QtCore.QRect(865, 443, 90, 22))
        self.p_crossover.setObjectName("p_crossover")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(250, 643, 591, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(250, 403, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.generation_size_1 = QtWidgets.QSpinBox(self.tab)
        self.generation_size_1.setGeometry(QtCore.QRect(865, 523, 90, 22))
        self.generation_size_1.setObjectName("generation_size_1")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(250, 93, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox_evr = QtWidgets.QComboBox(self.tab)
        self.comboBox_evr.setGeometry(QtCore.QRect(640, 210, 315, 31))
        self.comboBox_evr.setObjectName("comboBox_evr")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(250, 443, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_representation = QtWidgets.QComboBox(self.tab)
        self.comboBox_representation.setGeometry(QtCore.QRect(640, 270, 315, 31))
        self.comboBox_representation.setObjectName("comboBox_representation")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(990, 90, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setToolTip("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_evr = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_evr.setGeometry(QtCore.QRect(980, 210, 241, 31))
        self.lineEdit_evr.setObjectName("lineEdit_evr")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(80, 70, 1051, 621))
        font = QtGui.QFont()
        font.setFamily("MingLiU_HKSCS-ExtB")
        font.setPointSize(8)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(480, 20, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.label_9.setToolTipDuration(4)
        self.label_9.setMidLineWidth(12)
        self.label_9.setObjectName("label_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 710, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Запуск ГА"))
        self.label_3.setText(_translate("Form", "Введите размер поколения 1-го этапа"))
        self.label_11.setText(_translate("Form", "Выберите модель Голдберга"))
        self.label_13.setText(_translate("Form", "Выберите представление маршрута"))
        self.label_5.setText(_translate("Form", "Введите размер поколения 2-го этапа"))
        self.label.setText(_translate("Form", "Настройки для задачи коммивояжера"))
        self.label_4.setText(_translate("Form", "Введите количество повторений лучшего решения 1-го этапа"))
        self.label_12.setText(_translate("Form", "Выберите эвристический алгоритм для формирования начального поколения"))
        self.label_8.setText(_translate("Form", "Введите вероятность мутации в %"))
        self.label_14.setText(_translate("Form", "Выберите кроссовер"))
        self.label_6.setText(_translate("Form", "Введите количество повторений лучшего решения 2-го этапа"))
        self.label_2.setText(_translate("Form", "Введите количество запусков"))
        self.label_10.setText(_translate("Form", "Выберите задачу из списка"))
        self.label_7.setText(_translate("Form", "Введите вероятность кроссовера в %"))
        self.pushButton_2.setText(_translate("Form", "Выбор файла"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Настройки для задачи коммивояжера"))
        self.label_9.setText(_translate("Form", "Полученные результаты"))
        self.pushButton_3.setText(_translate("Form", "Сохранить в файл"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Полученные результаты"))
